### ISSUE TITLE
Implementar diferentes tipos de admin

### ISSUE THREAD

**Issue by semcomp-icmc** [semcomp/semcomp#163]
É necessário criar pelo menos 3 admins diferentes. 
1. Admin supremo: Tem acesso a qualquer coisa do Backoffice
2. Admin presença: Tem acesso para pegar presenças (Semcompona)
3. Admin Concursos: Admin que consegue ver os dados dos jogos bem como

**Comment by ThierryAra** [comment]
Ideia inicial (analisando as possibilidades):

---
Criar página de criar usuários no backoffice
Limitar o acesso da página apenas para o admin root
---
Adicionar rota para buscar a role do admin
Adicionar controller para buscar a role do admin
Buscar a role para decidir quais abas exibir
Criar requireAuth para as páginas baseadas na role do usuário
