### ISSUE TITLE
Backoffice | Fazer um botão de Beta ou Semcompona

### ISSUE THREAD

**Issue by semcomp-icmc** [semcomp/semcomp#166]
Adicionar alguma maneira de especificar qual a versão da Semcomp (Beta ou Alfa). Seria legal ter um botão swich para isso.
Motivação: Na Beta, por não ter casas, dá um erro se for fazer uma inscrição sem casa. Nesse caso precisaria ter uma flag que determina qual a versão da casa do lado do site principal. 
Pode ser feito através do banco ou com alguma variável global.

**Comment by ThierryAra** [comment]
Resolvi de uma outra forma, no commit [Remove a obrigatoriedade da existência de casas para o funcionamento](https://github.com/semcomp/semcomp/commit/8f01c8c4a02f853f2cf0d6f905be1488fe0cf162).
