### ISSUE TITLE
Verificar se a compra dos coffees está funcionando

### ISSUE THREAD

**Issue by ThierryAra** [semcomp/semcomp#172]
É necessário que o token pra compra esteja funcionando, esse token é o seguinte:
![image](https://github.com/semcomp/semcomp/assets/105522204/3b334379-9216-4a44-b344-1617afb02401)
Ele está disponível na pasta config que disponibilizamos para vocês.

Para você gerar esse token é preciso seguir esse passo a passo:
![image](https://github.com/semcomp/semcomp/assets/105522204/52d5f77b-853b-49bc-97a0-3c509ba75870)

Antes de testar para ter certeza de que está funcionando, entre em uma conta e descomente essa parte para aparecer as opções de compra:
![image](https://github.com/semcomp/semcomp/assets/105522204/3d9b4a36-43c7-46be-be28-600b7a520a28)
Dê uma explorada antes para conhecer melhor os passos da compra.

Use o token de teste que você criou para realizar uma transação de um valor pequeno para si mesmo e verificar que está funcionando a verificação do pix.

Para alterar o valor do pix gerado é preciso atualizar nessa parte do código:
![image](https://github.com/semcomp/semcomp/assets/105522204/acef4f10-3889-47c0-b4ca-0767d2f2368b)

**Comment by shogoshima** [comment]
Verificado ☆*: .｡. o(≧▽≦)o .｡.:*☆
