### ISSUE TITLE
Inscrições | Credenciamento | Pesquisa de inscritos

### ISSUE THREAD

**Issue by rebeca-vc** [semcomp/semcomp#214]
É necessário adequar a aba de usuários para que através do backoffice seja possível realizar o credenciamento e a verificação das pessoas inscritas na Semcomp. Para isso, é necessário adicionar uma barra de pesquisa para saber se a pessoa que tá lá na hora no balcão se inscreveu ou não sem que o membro fique procurando freneticamente entre as abas k.

![image](https://github.com/semcomp/semcomp/assets/105522204/12d5f33d-66f0-4769-a9f7-954cf4ffb8d7)

**Comment by KatielyLacerda** [comment]
quando a pesquisa for feita, é pra aparecer o nome dela se ela estiver inscrita certo? Agora é pra aparecer outras informações, como se ela tem kit ou n?

**Comment by ThierryAra** [comment]
> quando a pesquisa for feita, é pra aparecer o nome dela se ela estiver inscrita certo? Agora é pra aparecer outras informações, como se ela tem kit ou n?

Vish, desculpa, eu não vi essa pergunta (não sei se a Rebeca te respondeu na reunião), mas sim, o ideal é aparecer a linha inteira da tabela, se pudesse ser em tempo real ia ser legal também.
