### ISSUE TITLE
Front | Adicionar novamente as Conquistas no perfil

### ISSUE THREAD

**Issue by rebeca-vc** [semcomp/semcomp#216]
Esse é um trabalhinho além do front kkkkk Mas envolve ele também. Em algum momento da vida lááá na pandemia tinha um rolê de conquistas tipo as da steam, elas foram desativadas depois da Semcomp home edition, mas ainda estão em algum canto do código. Sua missão é encontrar o que temos de código restante dessa funcionalidade no código principal e restaurar isso.

Warning: Você não vai encontrar nenhuma conquista cadastrada no banco de dados, mas quando chegar nesse ponto chame um dos coordenadores para ver com você como que isso ficava armazenado.

**Comment by ThierryAra** [comment]
Adicionei novamente a página de conquistas ao backoffice com a criação e verificações, além de alterar o formato de utilização das imagens das conquistas, fazendo-as serem salvar em base64 no próprio banco. Também criei o switch de ativação/desativação das conquistas, adicionando os bloqueios necessários.
No app eu reabri as conquistas e adicionei um novo método de recebimento. Ele consiste em ler um QR Code chamando uma rota com o ID da conquista (apenas para usuários por enquanto); Essa opção está presente no card das conquistas, ativado clicando no ícone de câmera.
