### ISSUE TITLE
Backoffice | Presenças duplicadas

### ISSUE THREAD

**Issue by rebeca-vc** [semcomp/semcomp#217]
Na semcomp passada tivemos muitos problemas com a presença recolhida dos inscritos, pois muitas vezes ela ia duplicada (eu ACHO por que não fui atrás para descobrir o que rolou). Por isso, meu caro membro caríssimo do site você foi incumbido da missão de descobrir o que pode estar dando errado nas presenças. Elas são coletadas a partir dessas telas: 

![image](https://github.com/semcomp/semcomp/assets/105522204/f3872475-db8f-4b51-99bd-6867fe84b568)
![image](https://github.com/semcomp/semcomp/assets/105522204/4e6dc213-46c4-4139-9cad-36a9cf74082b)

Essa câmera scaneia o QR code disponível na tela do usuário, se precisar habilite o QR code no código principal.

**Comment by ThierryAra** [comment]
Não foi encontrado nenhum indício do problema
